name: survey_app
description: A simple survey app for balcony/garden design
version: 1.0.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_painter: ^0.5.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  pdf: ^3.8.0
  printing: ^5.9.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.0
  flutter_email_sender: ^5.0.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

